### ISSUE TITLE
environment setup

### ISSUE THREAD

**Issue by jzvolensky** [alina2204/contrastive_SSL_ship_detection#4]
Hi!

We are working on a project that is trying to implement this model. However, we are unable to set up the environment. 
¨pip3 install -r requirements.txt" fails due to unknown versions of which I can tell are ubuntu packages. 

The Dockerfile is incomplete and we cannot make it run without some further information about the actual environment used. 

Could you please explain in a bit more detail on how to get the environment running? Thanks!

**Comment by alina2204** [comment]
Hello, I am sorry that you have trouble setting up the environment. Unfortunately, I cannot access the original environment anymore; I know we worked on Ubuntu, but that is the only information I remember. If, in your case, setting up the environment through  `pip3 install requirements.txt` or using the Dockerfile does not work, I think installing manually the Python and PyTorch packages given in the Dockerfile would be enough to make everything work.

**Comment by jzvolensky** [comment]
Hey, thank you very much. I will try to do it manually. Have a good day!
